import test, {before, after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {transaction} from '../src/transaction.ts';
import {Pool} from 'pg';
import type {PoolClient} from 'pg';
import {migrate} from '../src/migrate.ts';
import {WorkspaceStore,sessionDigest} from '../src/workspace-store.ts';
import type {PageAddress} from '../src/workspace-store.ts';
import {WorkspaceError,schemaIdentifier} from '../src/validation.ts';

// Deliberately fails when infrastructure/opt-in is absent; no skipped/mock PASS.
const url=process.env.SCRIPTUM_VERIFICATION_DATABASE_URL;
if(!url||process.env.SCRIPTUM_ALLOW_VERIFICATION_SCHEMA!=='YES')throw new Error('Real PostgreSQL verification needs dedicated URL and SCRIPTUM_ALLOW_VERIFICATION_SCHEMA=YES');
const parsed=new URL(url);
if(!['127.0.0.1','localhost','[::1]'].includes(parsed.hostname))throw new Error('Verification database must use loopback');
const schema='wsverify_'+randomUUID().replaceAll('-',''),pool=new Pool({connectionString:url,max:8,application_name:schema}),store=new WorkspaceStore(pool,schema);
let suiteLock:PoolClient|undefined,ownedSchema=false,libraryKey:string;
let owner:string,editor:string,viewer:string,editorID:string,viewerID:string,target:PageAddress,revision:string;
const envelope=(keyReference:string=libraryKey)=>({ciphertext:randomBytes(64),nonce:randomBytes(12),digest:randomBytes(32),keyReference,version:1 as const});
async function identity(){const id=randomUUID(),token=randomBytes(32).toString('base64url');await pool.query(`INSERT INTO ${schemaIdentifier(schema)}.accounts(id,identity_issuer,identity_subject) VALUES($1,'synthetic-verification',$2)`,[id,id]);await pool.query(`INSERT INTO ${schemaIdentifier(schema)}.server_sessions(id,account_id,token_digest,expires_at) VALUES($1,$2,$3,clock_timestamp()+interval '1 hour')`,[randomUUID(),id,sessionDigest(token)]);return{id,token};}
async function registerKey(libraryID:string){const reference='synthetic:'+randomUUID();await pool.query(`INSERT INTO ${schemaIdentifier(schema)}.encryption_keys(reference,library_id) VALUES($1,$2)`,[reference,libraryID]);return reference;}
before(async()=>{const v=await pool.query<{server_version_num:string}>('SHOW server_version_num');assert.equal(Math.floor(Number(v.rows[0]!.server_version_num)/10000),18);suiteLock=await pool.connect();await suiteLock.query('SELECT pg_advisory_lock(hashtextextended($1,0))',['scriptum:verification:'+schema]);await pool.query(`CREATE SCHEMA ${schemaIdentifier(schema)}`);ownedSchema=true;await migrate(pool,schema);await migrate(pool,schema);owner=(await identity()).token;const e=await identity(),w=await identity();editor=e.token;editorID=e.id;viewer=w.token;viewerID=w.id;const library=await store.createLibrary(owner,'Synthetic ACL fixture'),space=await store.createSpace(owner,library,'Space');libraryKey=await registerKey(library);target={libraryID:library,spaceID:space,pageID:randomUUID()};revision=await store.createPage(owner,target,envelope());await store.setMembership(owner,{libraryID:library,kind:'library'},editorID,2);await store.setMembership(owner,{libraryID:library,kind:'library'},viewerID,1);});
after(async()=>{try{if(ownedSchema)await pool.query(`DROP SCHEMA ${schemaIdentifier(schema)} CASCADE`);}finally{if(suiteLock){try{await suiteLock.query('SELECT pg_advisory_unlock(hashtextextended($1,0))',['scriptum:verification:'+schema]);}finally{suiteLock.release();}}await pool.end();}});
test('real inherited viewer/editor, conflict rollback and encrypted persistence',async()=>{assert.equal((await store.readPage(viewer,target)).revision,revision);await assert.rejects(store.writePage(viewer,target,revision,envelope()),(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');const original=await store.readPage(owner,target);const updated=await store.writePage(editor,target,revision,envelope());const history=await pool.query<{source_ciphertext:Buffer}>(`SELECT source_ciphertext FROM ${schemaIdentifier(schema)}.page_revisions WHERE library_id=$1 AND space_id=$2 AND page_id=$3 AND revision=$4`,[target.libraryID,target.spaceID,target.pageID,revision]);assert.deepEqual(history.rows[0]?.source_ciphertext,original.envelope.ciphertext);await assert.rejects(store.writePage(editor,target,revision,envelope()),(e:unknown)=>e instanceof WorkspaceError&&e.code==='conflict');assert.equal((await store.readPage(owner,target)).revision,updated);revision=updated;});
test('explicit lower overrides and child grants never raise viewer parent',async()=>{await store.setMembership(owner,{...target,kind:'page'},editorID,1);await assert.rejects(store.writePage(editor,{libraryID:target.libraryID.toUpperCase(),spaceID:target.spaceID.toUpperCase(),pageID:target.pageID.toUpperCase()},revision,envelope()),(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');await assert.rejects(store.writePage(editor,target,revision,envelope()),(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');await store.revokeMembership(owner,{...target,kind:'page'},editorID);await store.setMembership(owner,{...target,kind:'page'},viewerID,3);await assert.rejects(store.writePage(viewer,target,revision,envelope()),(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');});
test('same page UUID in different libraries remains isolated',async()=>{const other=await store.createLibrary(owner,'Other'),space=await store.createSpace(owner,other,'Other');const second={libraryID:other,spaceID:space,pageID:target.pageID},key=await registerKey(other);await store.createPage(owner,second,envelope(key));await assert.rejects(store.createPage(owner,{...second,pageID:randomUUID()},envelope(libraryKey)),(e:unknown)=>(e as {code?:string}).code==='23503');await assert.rejects(store.readPage(editor,second),(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');assert.notEqual((await store.readPage(owner,second)).revision,(await store.readPage(owner,target)).revision);});
test('expired/revoked sessions and forged account tokens cannot authorize',async()=>{await assert.rejects(store.readPage(randomBytes(32).toString('base64url'),target),(e:unknown)=>e instanceof WorkspaceError&&e.code==='unauthenticated');const identityRow=await identity();await pool.query(`UPDATE ${schemaIdentifier(schema)}.server_sessions SET expires_at=clock_timestamp()-interval '1 second' WHERE account_id=$1`,[identityRow.id]);await assert.rejects(store.createLibrary(identityRow.token,'Denied'),(e:unknown)=>e instanceof WorkspaceError&&e.code==='unauthenticated');await pool.query(`UPDATE ${schemaIdentifier(schema)}.server_sessions SET revoked_at=clock_timestamp() WHERE token_digest=$1`,[sessionDigest(viewer)]);await assert.rejects(store.readPage(viewer,target),(e:unknown)=>e instanceof WorkspaceError&&e.code==='unauthenticated');});
test('fresh transaction after concurrent revocation denies queued writer',async()=>{const revoker=await pool.connect();try{await revoker.query('BEGIN');await revoker.query(`SELECT id FROM ${schemaIdentifier(schema)}.libraries WHERE id=$1 FOR UPDATE`,[target.libraryID]);await revoker.query(`DELETE FROM ${schemaIdentifier(schema)}.memberships WHERE library_id=$1 AND account_id=$2 AND resource_kind='library'`,[target.libraryID,editorID]);const queued=store.writePage(editor,target,revision,envelope());let blocked=false;for(let attempt=0;attempt<100;attempt++){const locks=await pool.query<{count:string}>("SELECT count(*) FROM pg_stat_activity WHERE application_name=$1 AND wait_event_type='Lock' AND query LIKE 'SELECT owner_account_id%'",[schema]);if(Number(locks.rows[0]?.count)>0){blocked=true;break;}await new Promise(resolve=>setTimeout(resolve,10));}assert.equal(blocked,true,'Writer must actually wait on the library lock');await revoker.query('COMMIT');await assert.rejects(queued,(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');assert.equal((await store.readPage(owner,target)).revision,revision);}catch(e){await revoker.query('ROLLBACK');throw e;}finally{revoker.release();}});

test('resource delegation ceiling prevents higher grant and restart migration is unchanged',async()=>{const library=await store.createLibrary(owner,'Ceiling fixture');await pool.query(`UPDATE ${schemaIdentifier(schema)}.libraries SET delegation_ceiling=1 WHERE id=$1`,[library]);const space=await store.createSpace(owner,library,'Restricted');await assert.rejects(store.setMembership(owner,{libraryID:library,kind:'space',spaceID:space},editorID,2),(e:unknown)=>e instanceof WorkspaceError&&e.code==='forbidden');const page={libraryID:library,spaceID:space,pageID:randomUUID()},key=await registerKey(library),encryption=envelope(key);const expected=await store.createPage(owner,page,encryption);const another=new WorkspaceStore(pool,schema);await migrate(pool,schema);const persisted=await another.readPage(owner,page);assert.equal(persisted.revision,expected);assert.deepEqual(persisted.envelope,encryption);});

test('historical A-to-B-to-A nonce reuse rejects without changing current/history/audit',async()=>{
  const original=await store.readPage(owner,target),a=envelope();
  const aRevision=await store.writePage(owner,target,original.revision,a),b=envelope();
  const bRevision=await store.writePage(owner,target,aRevision,b);
  const historyBefore=await pool.query(`SELECT revision,source_ciphertext,source_nonce FROM ${schemaIdentifier(schema)}.page_revisions WHERE library_id=$1 AND space_id=$2 AND page_id=$3 ORDER BY revision`,[target.libraryID,target.spaceID,target.pageID]);
  const auditsBefore=await pool.query<{count:string}>(`SELECT count(*) FROM ${schemaIdentifier(schema)}.audit WHERE library_id=$1`,[target.libraryID]);
  await assert.rejects(store.writePage(owner,target,bRevision,{...envelope(),nonce:a.nonce}), (error:unknown)=>(error as {code?:string}).code==='23505');
  assert.deepEqual(await store.readPage(owner,target),{revision:bRevision,envelope:b});
  const historyAfter=await pool.query(`SELECT revision,source_ciphertext,source_nonce FROM ${schemaIdentifier(schema)}.page_revisions WHERE library_id=$1 AND space_id=$2 AND page_id=$3 ORDER BY revision`,[target.libraryID,target.spaceID,target.pageID]);
  const auditsAfter=await pool.query(`SELECT count(*) FROM ${schemaIdentifier(schema)}.audit WHERE library_id=$1`,[target.libraryID]);
  assert.deepEqual(historyAfter.rows,historyBefore.rows);assert.deepEqual(auditsAfter.rows,auditsBefore.rows);revision=bRevision;
});

test('nonce claims are immutable and results bind the exact scheduled run target',async()=>{
  await assert.rejects(pool.query(`DELETE FROM ${schemaIdentifier(schema)}.nonce_usage WHERE key_reference=$1`,[libraryKey]),(e:unknown)=>(e as {code?:string}).code==='55000');
  const schedule=randomUUID(),run=randomUUID();
  const account=await pool.query<{owner_account_id:string}>(`SELECT owner_account_id FROM ${schemaIdentifier(schema)}.libraries WHERE id=$1`,[target.libraryID]);
  await pool.query(`INSERT INTO ${schemaIdentifier(schema)}.schedules(library_id,space_id,page_id,id,owner_account_id,generation,lifecycle,rule) VALUES($1,$2,$3,$4,$5,1,'draft','{}')`,[target.libraryID,target.spaceID,target.pageID,schedule,account.rows[0]!.owner_account_id]);
  await pool.query(`INSERT INTO ${schemaIdentifier(schema)}.runs(library_id,schedule_id,id,generation,scheduled_utc,state,space_id,page_id) VALUES($1,$2,$3,1,clock_timestamp(),'queued',$4,$5)`,[target.libraryID,schedule,run,target.spaceID,target.pageID]);
  const otherPage={...target,pageID:randomUUID()};await store.createPage(owner,otherPage,envelope());
  const encrypted=envelope();
  await assert.rejects(pool.query(`INSERT INTO ${schemaIdentifier(schema)}.results(library_id,run_id,id,space_id,page_id,base_revision,kind,payload_ciphertext,nonce,key_reference,source_digest) VALUES($1,$2,$3,$4,$5,$6,'summary',$7,$8,$9,$10)`,[target.libraryID,run,randomUUID(),target.spaceID,otherPage.pageID,randomUUID(),encrypted.ciphertext,encrypted.nonce,encrypted.keyReference,encrypted.digest]),(e:unknown)=>(e as {code?:string}).code==='23503');
});

async function legacyFixture(conflicting:boolean){
  const legacy='wsverify_'+randomUUID().replaceAll('-',''),lock=await pool.connect();let owned=false;
  try{
    await lock.query('SELECT pg_advisory_lock(hashtextextended($1,0))',['scriptum:verification:'+legacy]);
    await pool.query(`CREATE SCHEMA ${schemaIdentifier(legacy)}`);owned=true;
    const sql=await readFile(new URL('../sql/001_workspace.sql',import.meta.url),'utf8');
    const account=randomUUID(),token=randomBytes(32).toString('base64url');
    await transaction(pool,legacy,async client=>{await client.query(sql);await client.query('INSERT INTO schema_migrations(version,checksum) VALUES(1,$1)',[createHash('sha256').update(sql).digest('hex')]);await client.query("INSERT INTO accounts(id,identity_issuer,identity_subject) VALUES($1,'synthetic-legacy',$2)",[account,account]);await client.query("INSERT INTO server_sessions(id,account_id,token_digest,expires_at) VALUES($1,$2,$3,clock_timestamp()+interval '1 hour')",[randomUUID(),account,sessionDigest(token)]);});
    const service=new WorkspaceStore(pool,legacy),library=await service.createLibrary(token,'Legacy'),space=await service.createSpace(token,library,'Legacy');
    const address={libraryID:library,spaceID:space,pageID:randomUUID()},a=envelope('synthetic:legacy:'+randomUUID()),b=envelope(a.keyReference);
    const first=await service.createPage(token,address,a),second=await service.writePage(token,address,first,b);
    if(conflicting)await service.writePage(token,address,second,{...envelope(a.keyReference),nonce:a.nonce});
    const before=await service.readPage(token,address),history=await pool.query(`SELECT revision,source_ciphertext,source_nonce FROM ${schemaIdentifier(legacy)}.page_revisions ORDER BY revision`);
    if(conflicting){await assert.rejects(migrate(pool,legacy),(e:unknown)=>(e as {code?:string}).code==='23505');assert.deepEqual(await service.readPage(token,address),before);assert.deepEqual((await pool.query(`SELECT revision,source_ciphertext,source_nonce FROM ${schemaIdentifier(legacy)}.page_revisions ORDER BY revision`)).rows,history.rows);assert.equal((await pool.query(`SELECT version FROM ${schemaIdentifier(legacy)}.schema_migrations ORDER BY version`)).rows.length,1);const absent=await pool.query<{present:string|null}>('SELECT to_regclass($1) AS present',[legacy+'.nonce_usage']);assert.equal(absent.rows[0]?.present,null);}
    else{await migrate(pool,legacy);assert.deepEqual(await service.readPage(token,address),before);const seeded=await pool.query<{count:string}>(`SELECT count(*) FROM ${schemaIdentifier(legacy)}.nonce_usage`);assert.equal(Number(seeded.rows[0]?.count),2);await assert.rejects(service.writePage(token,address,before.revision,{...envelope(a.keyReference),nonce:a.nonce}),(e:unknown)=>(e as {code?:string}).code==='23505');}
  }finally{try{if(owned)await pool.query(`DROP SCHEMA ${schemaIdentifier(legacy)} CASCADE`);}finally{try{await lock.query('SELECT pg_advisory_unlock(hashtextextended($1,0))',['scriptum:verification:'+legacy]);}finally{lock.release();}}}
}
test('legacy migration seeds current/history claims without changing source',async()=>{await legacyFixture(false);});
test('legacy conflicting nonce migration rolls back without changing source/history/version',async()=>{await legacyFixture(true);});
